<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="hubert">

    <xacro:include filename="inertial_macros.xacro"/>

    <xacro:property name="chassis_radius" value="0.17"/>
    <xacro:property name="chassis_height" value="0.08"/>
    <xacro:property name="chassis_mass" value="3.5"/>

    <xacro:property name="chassis_clearance" value="0.01"/>


    <xacro:property name="wheel_radius" value="0.04"/>
    <xacro:property name="wheel_thickness" value="0.02"/>
    <xacro:property name="wheel_mass" value="0.05"/>
    <xacro:property name="wheel_offset_x" value="0"/>
    <xacro:property name="wheel_offset_y" value="0.11"/>
    <xacro:property name="wheel_offset_z" value="${wheel_radius}"/>

    <xacro:property name="clearance_epsilon" value="0.001"/>
    
    <xacro:property name="caster_wheel_radius" value="0.03"/>
    <xacro:property name="caster_wheel_mass" value="0.01"/>
    <xacro:property name="caster_wheel_offset_x" value="0.13"/>
    <xacro:property name="caster_wheel_offset_z" value="${caster_wheel_radius + clearance_epsilon}"/>

    <xacro:property name="mob_radius" value="0.04"/>
    <xacro:property name="mob_width" value="0.18"/>
    <xacro:property name="mob_mass" value="0.1"/>
    <xacro:property name="mob_offset_x" value="-0.1"/>
    <xacro:property name="mob_offset_z" value="${mob_radius + clearance_epsilon}"/>


    <material name="white">
        <color rgba="1 1 1 1" />
    </material>

    <material name="orange">
        <color rgba="1 0.3 0.1 1"/>
    </material>

    <material name="blue">
        <color rgba="0.2 0.2 1 1"/>
    </material>

    <material name="black">
        <color rgba="0 0 0 1"/>
    </material>



    <!-- BASE LINK -->

    <link name="base_link">

    </link>

    <!-- BASE_FOOTPRINT LINK -->
    
    <joint name = "base_footprint_joint" type = "fixed">
        <parent link = "base_link"/>
        <child link = "base_footprint"/>
        <origin xyz = "0 0 0 " rpy = "0 0 0"/>
    </joint>

    <link name = "base_footprint">
        
    </link>

    
    <!-- CHASSIS LINK -->

    <joint name="chassis_joint" type="fixed">
        <parent link="base_link"/>
        <child link="chassis"/>
        <origin xyz="0 0 ${chassis_clearance + (chassis_height/2) }"/>
    </joint>

    <link name="chassis">
        <visual>
            <origin xyz="0 0 0"/>
            <geometry>
                <cylinder radius="${chassis_radius}" length="${chassis_height}"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <origin xyz="0 0 0."/>
            <geometry>
                <cylinder radius="${chassis_radius}" length="${chassis_height}"/> 
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${chassis_mass}" radius="${chassis_radius}" length="${chassis_height}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>


    <gazebo reference="chassis">
        <material>Gazebo/White</material>
    </gazebo>
    
    <!-- LEFT WHEEL LINK -->

    <joint name="left_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="left_wheel"/>
        <origin xyz="${wheel_offset_x} ${wheel_offset_y} ${wheel_offset_z}" rpy="-${pi/2} 0 0" />
        <axis xyz="0 0 1"/>
    </joint>

    <link name="left_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <!-- use sphere for collision to avoid wheel drift in simulation -->
                <sphere radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" radius="${wheel_radius}" length="${wheel_thickness}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="left_wheel">
        <material>Gazebo/Blue</material>
    </gazebo>

    <!-- RIGHT WHEEL LINK -->

    <joint name="right_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="right_wheel"/>
        <origin xyz="${wheel_offset_x} ${-wheel_offset_y} ${wheel_offset_z}" rpy="${pi/2} 0 0" />
        <axis xyz="0 0 -1"/>
    </joint>

    <link name="right_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <!-- use sphere for collision to avoid wheel drift in simulation -->
                <sphere radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" radius="${wheel_radius}" length="${wheel_thickness}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>


    <gazebo reference="right_wheel">
        <material>Gazebo/Blue</material>
    </gazebo>

    <!-- CASTER WHEEL LINK -->

    <joint name="caster_wheel_joint" type="fixed">
        <parent link="base_link"/>
        <child link="caster_wheel"/>
        <origin xyz="${caster_wheel_offset_x} 0  ${caster_wheel_offset_z}"/>
    </joint>


    <link name="caster_wheel">
        <visual>
            <geometry>
                <sphere radius="${caster_wheel_radius}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${caster_wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_sphere mass="${caster_wheel_mass}" radius="${caster_wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_sphere>
    </link>

    <gazebo reference="caster_wheel">
        <material>Gazebo/Black</material>
        <mu1 value="0.001"/>
        <mu2 value="0.001"/>
    </gazebo>

    <!-- MOB -->

    <joint name="mob_joint" type="fixed">
        <parent link="base_link"/>
        <child link="mob"/>
        <origin xyz="${mob_offset_x} 0 ${mob_offset_z}" rpy="${pi/2} 0 0"/>
    </joint>


    <link name="mob">
        <visual>
            <geometry>
                <cylinder radius="${mob_radius}" length="${mob_width}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${mob_radius}" length="${mob_width}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${mob_mass}" radius="${mob_radius}" length="${mob_width}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="mob">
        <material>Gazebo/Grey</material>
        <mu1 value="0.001"/>
        <mu2 value="0.001"/>
    </gazebo>

</robot>